FROM registry.ng.bluemix.net/ibmliberty:javaee7
COPY ./bookingservice-java/server.xml /config/

RUN installUtility install --acceptLicense defaultServer

EXPOSE 80
ENV VCAP_APP_PORT=80
ENV SERVICE_NAME=booking

ADD ./bookingservice-java/build/libs/*.war /config/apps/