apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bookingservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: booking-deployment
    spec:
      containers:
      - env:
        - name: MONGO_HOST
          valueFrom:
            configMapKeyRef:
              name: mongo
              key: MONGO_HOST
        name: bookingservice-java
        image: bookingservice-java:latest
        ports:
          - containerPort: 9080
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: booking-service
  namespace: default
spec:
  ports:
    - port: 9080
  selector:
    name: booking-deployment
